"""Rev D stable development-controller configuration."""

import board

LOGGING = False
MIRROR_I2C = False

I2C_SCL = board.RX
I2C_SDA = board.TX
ADDRESS_PIN = board.A3
MODE_BUTTON = board.MISO
BUFFER_ENABLE = board.MOSI

# Validated half-array hardware SPI1 path: CH5 clock plus CH6 data.
DISPLAY_CLOCK = board.A0
DISPLAY_DATA = board.A1
SPI_BAUDRATE = 4_000_000

EYES_ADDRESS = 0x30
MOUTH_ADDRESS = 0x31
SPARE_ADDRESS = 0x32
DEVELOPMENT_ADDRESS = 0x33
BOTH_A0_THRESHOLD = 29_500
A0_A1_THRESHOLD = 38_200
A1_OPEN_THRESHOLD = 54_600

EYES_MODULE_COUNT = 2
EYES_MODULE_WIDTH = 9
EYES_MODULE_HEIGHT = 16
MOUTH_MODULE_COUNT = 3
MOUTH_MODULE_WIDTH = 5
MOUTH_MODULE_HEIGHT = 11

BRIGHTNESS = 0.08
BENDER_COLOR = (255, 110, 0)
STARTUP_DARK_SECONDS = 3.0
STARTUP_MESSAGE_SECONDS = 2.0
STARTUP_IDENTITY_SECONDS = 2.0
STARTUP_TEXT_FPS = 20
MESSAGE_TEXT_FPS = 10
MESSAGE_SCROLL_SLOWDOWN = 1
MODE_ANNOUNCEMENT_SECONDS = 3.0
FRAME_RATE = 10
MIN_BENDER_PAUSE_SECONDS = 1.0
MAX_BENDER_PAUSE_SECONDS = 4.0
BUTTON_DEBOUNCE_SECONDS = 0.05
